run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  gosec:
    excludes:
      - G115
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - fmt
          - os
          - github.com/kelseyhightower/envconfig
          - github.com/rs/zerolog
          - github.com/stretchr/testify/require
          - github.com/gorilla/mux
          - github.com/disintegration/imaging
          - github.com/cucumber/godog
          - github.com/merlex/otus-image-previewer/internal/config
          - github.com/merlex/otus-image-previewer/internal/http
          - github.com/merlex/otus-image-previewer/internal/logger
          - github.com/merlex/otus-image-previewer/internal/lru
          - github.com/merlex/otus-image-previewer/internal/model
          - github.com/merlex/otus-image-previewer/internal/service
          - github.com/merlex/otus-image-previewer/internal/util

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace