networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.11.16/28

services:
  integration_tests:
    build:
      context: ./
      dockerfile: ./integration/Dockerfile
    command: "true"
    links:
      - previewer
      - nginx
    networks:
      - app
  nginx:
    build:
      context: ./
      dockerfile: ./build/nginx/Dockerfile
    restart: on-failure
    ports:
        - "8181:80"
    expose:
        - 80
    networks:
      - app
  previewer:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    restart: on-failure
    ports:
      - "8585:8585"
    expose:
      - 8585
    environment:
      LOGGER_LEVEL: info
      LOGGER_FORMAT: json
      LOGGER_FILE: "/opt/previewer/previewer.log"
      LOGGER_LOG_TO_FILE: false
      LOGGER_LOG_TO_CONSOLE: true
      CACHE_DIR: "/tmp/"
      CACHE_CAPACITY: "10"
      HTTP_IP: 0.0.0.0
      HTTP_PORT: 8585
    networks:
      - app
